name = "iog/validators"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'iog/validators'"

[repository]
user = "iog"
project = "validators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
